name: AppWright Test

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AppWright
        run: npm install -g appwright

      - name: Install Python dependencies
        run: |
          pip install requests flask redis==3.5.3 rq

      - name: Show test script (for debug)
        run: |
          cat tests/onboarding.spec.js || echo "Test script not found!"

      - name: Start backend server
        run: |
          nohup python qualgent-backend-challenge/job_server/server.py > server.log 2>&1 &
          sleep 30

      - name: Start RQ worker
        run: |
          nohup rq worker > worker.log 2>&1 &
          sleep 5

      - name: Submit test job
        run: |
          python qualgent-backend-challenge/cli/qgjob.py submit \
            --org-id=qualgent \
            --app-version-id=xyz123 \
            --test=tests/onboarding.spec.js \
            --target=emulator > job_output.txt

      - name: Print server log on failure
        if: failure()
        run: cat server.log

      - name: Print worker log on failure
        if: failure()
        run: cat worker.log